export const DEFAULT_CELL_ROW_COUNT = 100; //  行数
export const DEFAULT_CELL_COL_COUNT = 100; //  列数
export const DEFAULT_CELL_MIN_WIDTH = 30; //  列最小宽度
export const DEFAULT_CELL_MIN_HEIGHT = 20; //  行最小高度
export const DEFAULT_CELL_WIDTH = 100; //  列宽度
export const DEFAULT_CELL_HEIGHT = 25; //  行高度
export const DEFAULT_INDEX_CELL_WIDTH = 50; //  行号列宽度
export const DEFAULT_CELL_TEXT_FONT_FAMILY = "sans-serif"; //  单元格字体
export const DEFAULT_CELL_TEXT_FONT_SIZE = 12; //  单元格字体大小
export const DEFAULT_CELL_TEXT_BOLD = false; //  单元格字体是否加粗
export const DEFAULT_CELL_TEXT_ITALIC = false; //  单元格字体是否倾斜
export const DEFAULT_CELL_TEXT_UNDERLINE = false; //  单元格字体是否有下划线
export const DEFAULT_CELL_TEXT_BACKGROUND_COLOR = "#fff"; //  单元格背景颜色
export const DEFAULT_CELL_TEXT_COLOR = "#000"; //  单元格字体颜色
export const DEFAULT_CELL_TEXT_ALIGN = "center"; //  单元格字体对齐方式
export const DEFAULT_CELL_LINE_SOLID = false; //  单元格是否有实线边框
export const DEFAULT_CELL_LINE_BOLD = false; //  单元格边框是否加粗
export const DEFAULT_CELL_LINE_DASH = [3, 5]; //  单元格虚线边框样式
export const DEFAULT_CELL_LINE_COLOR = "#ccc"; //  单元格边框颜色
export const DEFAULT_CELL_PADDING = 10; //  单元格内边距
export const DEFAULT_FIXED_CELL_BACKGROUND_COLOR = "rgb(238, 238, 238)"; //  冻结单元格背景颜色
export const DEFAULT_FIXED_CELL_COLOR = "rgb(141, 87, 87)"; //  冻结单元格字体颜色
export const DEVIATION_COMPARE_VALUE = 10e-6; //  浮点数比较误差值
export const DEFAULT_GRADIENT_OFFSET = 6; //  渐变偏移量
export const DEFAULT_GRADIENT_START_COLOR = "rgba(0, 0, 0, 0.12)"; //  渐变起始颜色
export const DEFAULT_GRADIENT_STOP_COLOR = "transparent"; //  渐变终止颜色
export const RESIZE_ROW_SIZE = 5; //  行调整落焦判定范围
export const RESIZE_COL_SIZE = 10; //  列调整落焦判定范围
export const DEFAULT_RESIZER_LINE_WIDTH = 2; //  调整大小线宽度
export const DEFAULT_RESIZER_LINE_DASH = [3, 5]; //  调整大小线虚线样式
export const DEFAULT_RESIZER_LINE_COLOR = "rgb(75, 137, 255)"; //  调整大小线颜色
export const DEFAULT_CELL_SELECTED_BORDER_COLOR = "rgb(75, 137, 255)"; //  选中单元格边框颜色
export const DEFAULT_CELL_FILLING_BORDER_COLOR = "#d9363e"; //  填充单元格边框颜色
export const DEFAULT_CELL_FILLING_BORDER_WIDTH = 1; //  填充单元格边框宽度
export const DEFAULT_CELL_FILLING_LINE_DASH = [1, 3]; //  填充单元格虚线边框样式
export const DEFAULT_CELL_SELECTED_BACKGROUND_COLOR = "rgba(0, 94, 255, 0.1)"; //  选中单元格背景颜色
export const DEFAULT_CELL_SELECTED_FIXED_CELL_LINE_WIDTH = 2; //  选中冻结单元格边框宽度
export const DEFAULT_CELL_DIAGONAL_LINE_WIDTH = 0.5; //  单元格对角线边框宽度
export const DEFAULT_CELL_DIAGONAL_LINE_COLOR = "rgb(75, 137, 255)"; //  单元格对角线边框颜色
export const DEFAULT_CELL_DIAGONAL_TEXT_COLOR = "#000"; //  单元格对角线字体颜色
export const DEFAULT_CELL_DIAGONAL_TEXT_FONT_SIZE = 12; //  单元格对角线字体大小
export const DEFAULT_SCROLLBAR_TRACK_SIZE = 16; //  滚动条轨道尺寸
export const DEFAULT_SCROLLBAR_THUMB_SIZE = 16; //  滚动条滑块尺寸
export const DEFAULT_SCROLLBAR_TRACK_BORDER_COLOR = "#ebeef5"; //  滚动条轨道边框颜色
export const DEFAULT_SCROLLBAR_TRACK_BACKGROUND_COLOR = "#f1f1f1"; //  滚动条轨道背景颜色
export const DEFAULT_SCROLLBAR_THUMB_DRAGGING_COLOR = "#787878"; //  滚动条滑块拖拽颜色
export const DEFAULT_SCROLLBAR_THUMB_BACKGROUND_COLOR = "#c1c1c1"; //  滚动条滑块背景颜色
export const DEFAULT_SCROLLBAR_THUMB_MIN_SIZE = 20; //  滚动条滑块最小尺寸
export const DEFAULT_FILL_HANDLE_SIZE = 4; //  填充手柄尺寸
export const DEFAULT_FILL_HANDLE_BACKGROUND_COLOR = "rgb(75, 137, 255)"; //  填充手柄背景颜色
export const DEFAULT_FILL_HANDLE_BORDER_COLOR = "#fff"; //  填充手柄边框颜色
export const DEFAULT_FILL_HANDLE_BORDER_WIDTH = 1; //  填充手柄边框宽度
export const DEFAULT_CELL_INPUT_BACKGROUND_COLOR = "#fff"; //  单元格输入框背景颜色
export const DEFAULT_CELL_INPUT_COLOR = "#606266"; //  单元格输入框字体颜色
export const DEFAULT_CELL_INPUT_FONT_SIZE = 14; //  单元格输入框字体大小
export const DEFAULT_CELL_INPUT_FONT_FAMILY = "Helvetica"; //  单元格输入框字体
export const DEFAULT_CELL_INPUT_PLACEHOLDER_COLOR = "#ccc4d6"; //  单元格输入框占位符颜色
export const DEFAULT_CELL_INPUT_MARGIN = 1; //  单元格输入框内边距
