const data = {
  "colWidth": [
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100
  ],
  "configData": [
    [
      {
        "cellConfig": {
          "basicStyle": {
            "alignTypeDict": "none",
            "border": "unset",
            "colorFill": "#fff",
            "font": "sans-serif",
            "fontBold": false,
            "fontColor": "#373737",
            "fontSize": 12,
            "italic": false,
            "underline": false
          },
          "otherStyle": {
            "displayType": "plainText",
            "imageLayoutDict": "adapt",
            "textControlDict": "word_wrap",
            "textDirectionDict": "crosswise"
          }
        },
        "cellTypeDict": "datasets",
        "cellValue": "通行费堵漏增收,工程监理费,工会经费（个人部分）,项目投资款,商业汇票资金,专用材料,缺陷责任期成本,劳务派遣费,管道改造,预收售房订金,宣传费,可供出售金融资产公允价值变动损益,调度收入,线下销售业务,包装材料,兴业银行,惠罗公路,代管商品款,展销费,利息支出",
        "condition": [],
        "displayType": "plainText"
      },
      {
        "cellConfig": {
          "basicStyle": {
            "alignTypeDict": "none",
            "border": "unset",
            "colorFill": "#fff",
            "font": "sans-serif",
            "fontBold": false,
            "fontColor": "#373737",
            "fontSize": 12,
            "italic": false,
            "underline": false
          },
          "otherStyle": {
            "displayType": "plainText",
            "imageLayoutDict": "adapt",
            "textControlDict": "word_wrap",
            "textDirectionDict": "crosswise"
          }
        },
        "cellTypeDict": "static",
        "cellValue": null,
        "condition": [],
        "displayType": "plainText"
      },
      {
        "cellConfig": {
          "basicStyle": {
            "alignTypeDict": "none",
            "border": "1px solid #ef1313",
            "colorFill": "#fff",
            "font": "sans-serif",
            "fontBold": false,
            "fontColor": "#373737",
            "fontSize": 12,
            "italic": false,
            "underline": false
          },
          "otherStyle": {
            "displayType": "plainText",
            "imageLayoutDict": "adapt",
            "textControlDict": "word_wrap",
            "textDirectionDict": "crosswise"
          }
        },
        "cellTypeDict": "static",
        "cellValue": "测试边界",
        "condition": [],
        "displayType": "plainText"
      },
      {
        "cellConfig": {
          "basicStyle": {
            "alignTypeDict": "none",
            "border": "unset",
            "colorFill": "#fff",
            "font": "sans-serif",
            "fontBold": false,
            "fontColor": "#373737",
            "fontSize": 12,
            "italic": false,
            "underline": false
          },
          "otherStyle": {
            "displayType": "plainText",
            "imageLayoutDict": "adapt",
            "textControlDict": "word_wrap",
            "textDirectionDict": "crosswise"
          }
        },
        "cellTypeDict": "static",
        "cellValue": null,
        "condition": [],
        "displayType": "plainText"
      }
    ],
    [
      {
        "cellConfig": {
          "basicStyle": {
            "alignTypeDict": "none",
            "border": "unset",
            "colorFill": "#fff",
            "font": "sans-serif",
            "fontBold": false,
            "fontColor": "#373737",
            "fontSize": 12,
            "italic": false,
            "underline": false
          },
          "otherStyle": {
            "displayType": "plainText",
            "imageLayoutDict": "adapt",
            "textControlDict": "word_wrap",
            "textDirectionDict": "crosswise"
          }
        },
        "cellTypeDict": "static",
        "cellValue": 1,
        "condition": [],
        "displayType": "plainText"
      },
      {
        "cellConfig": {
          "basicStyle": {
            "alignTypeDict": "none",
            "border": "unset",
            "colorFill": "#fff",
            "font": "sans-serif",
            "fontBold": false,
            "fontColor": "#373737",
            "fontSize": 12,
            "italic": false,
            "underline": false
          },
          "otherStyle": {
            "displayType": "plainText",
            "imageLayoutDict": "adapt",
            "textControlDict": "word_wrap",
            "textDirectionDict": "crosswise"
          }
        },
        "cellTypeDict": "static",
        "cellValue": 2,
        "condition": [],
        "displayType": "plainText"
      },
      null,
      null
    ]
  ],
  "frame": [],
  "freeze": {
    "freezeCol": 0,
    "freezeRow": 0
  },
  "logInfo": "",
  "mergeCell": [
    {
      "col": 2,
      "colspan": 2,
      "point": "B0",
      "row": 0,
      "rowspan": 1
    },
    {
      "col": 0,
      "colspan": 2,
      "point": "null0",
      "row": 0,
      "rowspan": 1
    }
  ],
  "rowHeight": [
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23,
    23
  ]
}